version: '3'
volumes:
  docker_volume:
networks:
  docker_network:
    driver: bridge
services:
  ui:
    build: ui/
    ports:
    - '3000:3000'
    networks:
      - docker_network
    depends_on:
      - 'db'
    volumes:
      - type: bind
        source: ./ui/src
        target: /app/src
  api:
    build: api/
    ports:
      - '3001:3001'
    networks:
      - docker_network
    depends_on:
      - 'db'
    volumes:
      - type: bind
        source: ./api
        target: /app
    environment:
      - DATABASE_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=docker
      - POSTGRES_DB=docker_db
      - POSTGRES_PORT=5432
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - docker_volume:/var/lib/postgresql/data
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=docker
      - POSTGRES_DB=docker_db
      - POSTGRES_PORT=5432